[i18n-redesign] correction of existing language specific sample data
vivo-project/sample-data pull request #8
Opened 2022-12-06 09:34 UTC by chenejac

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3801](https://github.com/vivo-project/VIVO/issues/3801)

# What does this pull request do?

- Extension of language specific sample data with missing translations
- Adding sample data for Serbian

# How should this be tested?
Follow the instructions described at [PR](https://github.com/vivo-project/VIVO/pull/3798#issuecomment-1337278004) and use sample data ttl files from this PR.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers

2022-12-06 10:06 UTC, bkampe requested changes

2022-12-06 10:06 UTC, bkampe commented on i18n/sample-data-i18n-de_DE.ttl
> +  vcard:title  "(German translation) Professor and Associate Dean"@de-DE ;
```suggestion
  vcard:title  "Professor und stellvertretender Dekan"@de-DE ;
```

2022-12-06 10:06 UTC, bkampe commented on i18n/sample-data-i18n-de_DE.ttl
> +  vivo:overview "(German translation)The Physics Department is in the College of Science of Sample University"@de-DE ;
```suggestion
  vivo:overview "Das Fachgebiet Physik befindet sich an der Fakultät 1 der Hochschule."@de-DE ;
```

2022-12-06 10:12 UTC, bkampe approved these changes

2022-12-09 15:44 UTC, michel-heon approved these changes

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_CA.ttl
> +  vivo:overview "(French Canadian translation) The Physics Department is in the College of Science of Sample University"@fr-CA ;
```suggestion
  vivo:overview "Le département de Physique fait partie du Collège des Sciences de l'Université Exemple."@fr-CA ;
```

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_CA.ttl
> +  vcard:title  "(French Canadian translation) Professor and Associate Dean"@fr-CA ;
```suggestion
  vcard:title  "Professeur et Doyen associé"@fr-CA ;
```

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_CA.ttl
>    rdfs:label "Peters, Jasper I superviseur de Martinez, Claudia (Postdoc)"@fr-CA ;
```suggestion
  rdfs:label "Peters, Jasper I est le superviseur de Martinez, Claudia (Postdoc)"@fr-CA ;
```

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_FR.ttl
> +  vivo:overview "(French France translation) The Physics Department is in the College of Science of Sample University"@fr-FR ;
```suggestion
  vivo:overview "Le département de Physique fait partie du Collège des Sciences de l'Université Exemple de France"@fr-FR ;
```

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_FR.ttl
> +  vcard:title  "(French France translation) Professor and Associate Dean"@fr-FR ;
```suggestion
  vcard:title  "Professeur et Doyen associé"@fr-FR ;
```

2022-12-09 15:44 UTC, michel-heon commented on i18n/sample-data-i18n-fr_FR.ttl
>    rdfs:label "Peters, Jasper I superviseur de Martinez, Claudia (Postdoc)"@fr-FR ;
```suggestion
  rdfs:label "Peters, Jasper I est le superviseur de Martinez, Claudia (Postdoc)"@fr-FR ;
```

2022-12-12 14:36 UTC, litvinovg approved these changes

2022-12-12 20:56 UTC, merged